### PR TITLE
Move MainApiException and MainApiHeader

### PR DESCRIPTION
**Pull request by phiz71**

### CODE REVIEW

**Comment by phiz71** [comment]
@javadch : I think you will like this PR ;)

**Comment by javadch** [comment]
The `ResourceResponse` class has an import: `io.swagger.server.api.MainApiHeader`. This is wrong, while I have provided a custom package name during code generation. The `MainApiHeader` is in the right custom package, but the import is wrong. It affects all the calls to the `ResourceResponse.addHeader` methods. I have not checked other files!

**Comment by phiz71** [comment]
oops, I've hardcoded `io.swagger.server.api.MainApiHeader` in the ResourceResponse template 😓 .
Instead of using `{{invokerPackage}}`.. Sorry ^^

**Comment by javadch** [comment]
Let me know when you committed the fix ;-)

**Comment by phiz71** [comment]
Done

**Pull request merged**
