### PR TITLE
#22 support swagger security definitions

### PR DESCRIPTION
**Pull request by lopesmcc**
This is still incomplete. Sill missing:
- OAuth2 support.
- Change MainApiVerticle to pass AuthHandlers to the SwaggerRouter when the security definitions exist in the spec.

Help is appreciated to identify if the implemented approach is a good one.

### CODE REVIEW

**Comment by phiz71** [comment]
Thx, you did a great job !
I've added some tests and fixed a small bug.

However, I'm afraid extending `Routingcontext` and doing our own chaining of handlers is too complicated. I wonder if we could use `ChainAuth` to chain providers instead. 
What do you think of this ?

**Comment by lopesmcc** [comment]
Unfortunately `ChainAuth` is for `AuthProvider`s and not `AuthHandler`s, which makes it hard to apply to our use-case.
`AuthProvider`s are containers for the logic that authorizes something, and need to be provided.
`AuthHandler` is what integrates with the router, will read from the HTTP request whatever is required, and pass that to the `AuthProvider`. (OAuth is a bit different..)

Another problem is that we need to handle the OR condition and the AND condition when applying authentication handling to an operation. More details here: https://swagger.io/docs/specification/authentication/

Security spec example copied from the above link:
```
security:
  - A
  - B

 # A OR B authentication types can be used


security:
  - A
    B

 # A AND B  authentication types must be used


security:
  - A
    B
  - C
    D

 # (A AND B) OR (C AND D) authentication types can be used
```
This makes it a lot harder to simply use a chain.

**Comment by phiz71** [comment]
I think `ChainAuth` could have worked if there were only "OR" conditions. I think we could have a built our own customr provider by adding the right `authProvider` provided in SwaggerRouter parameter.
But you're right, it is certain that it wouldn't have worked with the "AND" condition.

I will post this problem on the [Vertx forum](https://groups.google.com/forum/#!forum/vertx). Maybe Someone has already faced this issue.

**Comment by phiz71** [comment]
https://groups.google.com/forum/#!topic/vertx/DMadoYr4Rrg

**Comment by lopesmcc** [comment]
Something else related to this that I'm trying to figure out is how to share Vert.x authenticated principal information (`RoutingContext.user().principal()`) with the Api implementation.

So far I've set a `configureMessage` function that passes the principal information I need to the verticle using message headers, but now I need a way to pass that to the actual API implementation.

What do you think of a generator option called "propagateHeaders", that when active, will always add a `MultiMap` parameter to each operation, and the verticle will use that to pass the message headers?

Example of API with `propagateHeaders` as false:
```java
...
    Completable deleteDashboardConfiguration(String dashboardId,String tier,String organizationId);
...
```

With `propagateHeaders` as true:
```java
...
    Completable deleteDashboardConfiguration(String dashboardId,String tier,String organizationId,MultiMap headers);
...
```

Another option would be to explicitly only propagate the vertx authentication `User` to the operations, although I find that if we have the capability to change the message headers (using `configureMessage`), then it might be useful to have a way to access that within the API implementations.

**Comment by phiz71** [comment]
I think adding the `User` to the operations that need security is a good idea. Interfaces could be generated only using the swagger definition and this would not be necessary to create a new generation option.
I just don't know if a `User` can be sent on the eventBus ; I think it's possible, but never try it.

However, I like your idea of propagating headers from the verticle to the implementation. And an option in the generator to add the MultiMap may be a good thing. It could be helpful if you want to send back XML instead of JSON for instance, or if you want to mange some custom headers.

**Comment by lopesmcc** [comment]
👍  I'll work on this a bit tomorrow.

**Comment by phiz71** [comment]
I don't know if you read the answer of Paulo Lopes. Chaining handlers will be possible in the next release of Vert.X (3.5.0). However, as it allows only 'OR' logic in chaining, I will propose a PR for a GroupedHandler which will allows the 'AND' logic.

But for the moment, your solution works very well 👍 .

**Comment by phiz71** [comment]
When you write :
> Change MainApiVerticle to pass AuthHandlers to the SwaggerRouter when the security definitions exist in the spec.

Do you mean Auth**Providers** ? 😉 

I have thought of generating an interface with as many "get" operation as "Security Definitions" in the swagger file. For instance, with a swagger like this :
```yaml
api_key:
  type: apiKey
  name: api_key
  in: header
petstore_auth:
  type: oauth2
  authorizationUrl: http://swagger.io/api/oauth/dialog
  flow: implicit
  scopes:
    write:pets: modify pets in your account
    read:pets: read your pets
```
the interface could look like this :
```java
public interface AuthProvidersFactory {
  // one method per securityDefinition ...
  AuthProvider getApiKeyAuthProvider();
  
  AuthProvider getPetstoreAuthAuthProvider();
  ...
    
  //... or one method with the name as parameter ...
  AuthProvider getAuthProviderByName(String securityDefinitionName);
  
  //... or one method for all AuthProviders 
  Map<String, AuthProvider> getApiAuthProviders();
  
}
```
The implementation would have to be coded.
Whet do you think of that ?

**Comment by lopesmcc** [comment]
@phiz71, yep, I meant AuthProviders.
Your proposal looks good to me.

Haven't had the time yet to do the `User` parameter improvement. Might start today.

It would be nice to have someone more experienced with OAuth2 to help integrate it.

**Comment by lopesmcc** [comment]
@phiz71 
I was looking into how to serialize/deserialize the User object, and am thinking of doing it like this:
- for the User to be propagated to the API, it would need to implement the `ClusterSerializable` interface. It's something that vertx own `AbstractUser` already does, so I decided to re-use it in our use-case.
- **a side note** is that extending `AbstractUser` is usually not enough, as it only serializes/deserializes data within the `AbstractUser` class (cached permissions). It does not, for example, serialize/deserialize the `principal` content.
- Example on the code that serializes the `user` and adds it to the eventbus message:
```java
    private static void addAuthUserHeader(RoutingContext context, DeliveryOptions deliveryOptions) {
        // re-using vertx UserHolder to serialize the `User` object
        Buffer buffer = Buffer.buffer();
        new UserHolder(context).writeToBuffer(buffer);
        deliveryOptions.addHeader(AUTH_USER_HEADER_KEY, buffer.toString());
    }
```
- On the API verticle, the logic that deserializes the `user` can be the following:
```java
    // unfinished code - missing exception handling, organization, etc.
    User user = null;
    String serializedUser = message.headers().get(SwaggerRouter.AUTH_USER_HEADER_KEY);
    if (serializedUser != null && !serializedUser.isEmpty()) {
        Buffer buffer = Buffer.buffer(serializedUser);
        UserHolder userHolder = new UserHolder();
        userHolder.readFromBuffer(0, buffer);
        user = userHolder.user;
        user.setAuthProvider(SwaggerCodegen.getAuthProviderByName(authProviderName));
    }
```
- Change the API interface generated code to receive a `user` variable whenever the operation has security definitions.

You probably noticed the `user.setAuthProvider` line. This method is already within the `User` interface, and we should honor it.
It's also useful, for example, when the `User` implementation requires a http client or DB client to retrieve the permissions - this way we can store that client within the authProvider, and keep the `User` as a simple data object.

I was thinking of having the SwaggerRouter store all the AuthProviders statically, and expose a them in a method similar to the one in the `AuthProvidersFactory`: `getAuthProviderByName(String securityDefinitionName)`.

**The issue now is how to pass the AuthProvider name to the verticles...**
We also can't simply use the information from the swagger spec - because of the OR/ANDs, it is unknown which exact AuthProvider was successful.
One solution would be to have the `User` store it... but then we would have to require the users to implement our own extension of `User`, that would have a `getAuthProviderName` method.

Sorry for the info dump. I am a bit unsure of the `AuthProvider` name solution, and any help is appreciated.

**Comment by lopesmcc** [comment]
Committed the User propagation logic. Please review @phiz71

**Comment by phiz71** [comment]
Really good job !
If you want to avoid AbstractUser extension, maybe the authProvider name could be added in the eventBus header, as it is done for the User.
I will have a closer look later.

**Comment by lopesmcc** [comment]
@phiz71 Yeah, I did think of that at the time, but dismissed it because I only had the User available within the RoutingContext, but now that I think of it again, we can simply store the name within the context when the `SwaggerAuthHandler` processes the request...

Will do that now and should have a PR update soon.

**Comment by lopesmcc** [comment]
@phiz71 Done the change. No more ApiUser. Now we can simply use the User. Cleaner and simpler. Thanks :)

**Comment by phiz71** [comment]
@lopesmcc : Congratulations !
Would you mind if I merge this PR, even if OAuth2 is not supported yet ?

**Comment by lopesmcc** [comment]
@phiz71 sound good to me

**Pull request merged**
