### PR TITLE
adding the possibility to generate JsonObject instead of POJO

### LINKED ISSUE #86: The code-gen to have an option to generate JsonObjects for the Swagger definitions, instead of POJOs
I have a set of services that work with  MongoDB backend and receive native JSON data.
I want to send this data to the client, but because the Swagger definitions are generated as POJOs, I have to materialize the received JSON objects to Java classes. Later, in the Verticles, these Java objects are once more serialized as JSON and sent to the requesting client.  I suggest these two transformations are just waste of CPU and Memory! It would be good to have a switch to tell the code-gen to generate JsonObjects from the  Swagger definitions. In this case, instead of <Entity> e.g., User, Product, and Store, only JsonObject is used and passed between layers. Also, the Verticles do not need to convert POJOs to JSON and make them pretty before sending them to clients.
The same concept should apply to lists and arrays of objects.

### PR DESCRIPTION
**Pull request by phiz71**
Fix #86

### CODE REVIEW

**Comment by javadch** [comment]
I just checked out the `86_PlainOldJsonObject` branch and did `mvn clean install`, then on my project, I did `mvn clean package`. It fails with the following errors. At the same time, it compiles when I use the `master` branch. So there should be a breaking change in the PR, or something that is responsible to generate `VerticleHelper` has not been pushed. 

I guess it is related to `io.swagger.server.api.MainApiException;` in `VerticleHelper`, that does not use the configured package name! Maybe this issue appears somewhere else, too.

`
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.3:compile (default-compile) on project server.pfa: Compilation failure: Compilation failure:
[ERROR] /D:/workspaces/swf/2/server.pfa/target/generated-sources/java/com/swf/server/pfa/handlers/util/VerticleHelper.java:[5,29] package io.swagger.server.api does not exist
[ERROR] /D:/workspaces/swf/2/server.pfa/target/generated-sources/java/com/swf/server/pfa/handlers/util/VerticleHelper.java:[46,36] package MainApiException does not exist
[ERROR] /D:/workspaces/swf/2/server.pfa/target/generated-sources/java/com/swf/server/pfa/handlers/util/VerticleHelper.java:[47,48] package MainApiException does not exist
[ERROR] /D:/workspaces/swf/2/server.pfa/target/generated-sources/java/com/swf/server/pfa/handlers/util/VerticleHelper.java:[49,30] cannot find symbol
[ERROR] symbol:   class MainApiException
[ERROR] location: class com.swf.server.pfa.handlers.util.VerticleHelper
[ERROR] /D:/workspaces/swf/2/server.pfa/target/generated-sources/java/com/swf/server/pfa/handlers/util/VerticleHelper.java:[50,22] cannot find symbol
[ERROR] symbol:   class MainApiException
[ERROR] location: class com.swf.server.pfa.handlers.util.VerticleHelper
[ERROR] /D:/workspaces/swf/2/server.pfa/target/generated-sources/java/com/swf/server/pfa/handlers/util/VerticleHelper.java:[51,31] cannot find symbol
[ERROR] symbol:   class MainApiException
[ERROR] location: class com.swf.server.pfa.handlers.util.VerticleHelper
[ERROR] /D:/workspaces/swf/2/server.pfa/target/generated-sources/java/com/swf/server/pfa/handlers/util/VerticleHelper.java:[52,42] cannot find symbol
[ERROR] symbol:   class MainApiException
[ERROR] location: class com.swf.server.pfa.handlers.util.VerticleHelper
`

**Comment by phiz71** [comment]
I've hardcoded the import (once again). Sorry.
It's fixed.

**Comment by javadch** [comment]
A spec path e.g., `getProducts` that returns a list of `Product`s should generate a:
`public void listProducts(Handler<AsyncResult<ResourceResponse<List<Product>>>> handler)` in its `xVerticleApi` but it generates `void listProducts(Handler<AsyncResult<ResourceResponse<JsonArray>>> handler)`.
Because generally, the implementations work with lists and do not care whether the objects are JSON or not, it would be better to have the API methods accepts lists of entities. It is also more type-safe!

**Comment by javadch** [comment]
I am looking at vertx JsonArray, seems no need to change anything! JsonArray accepts a list as its constructor's parameter.

**Comment by javadch** [comment]
It works fine. However, it has a problem with not-provided parameters.
For example, in this url `www.example.com/api/loans?status=x&page=1&size=10` the `LoansApiVerticle` has a `listLoansHandler` method that checks for the `page` parameter like this: `          if(message.body().getString("page") != null)`. Now, if the page parameter is not provided (it is optional), the `getString` method throws an exception and causes the request to fail! I would suggest, for optional parameters, to first check whether the `message.body()` contains the parameter and if so, then try to get its value. If the key is available, then `JsonObject` itself has a `getInteger` which can be used; it does the type checks/casting required. It also provides get operators for many other types.

**Comment by javadch** [comment]
I just filed another issue (#90) for the problem mentioned in the previous comment. So, you can proceed by  accepting this PR

**Pull request merged**
